FROM node:22-alpine

RUN apk add --no-cache python3 make g++

WORKDIR /app

COPY package*.json ./
COPY server/package*.json ./server/
COPY agent-service/package*.json ./agent-service/
COPY frontend/package*.json ./frontend/
RUN npm install

COPY . .

ENV NODE_ENV=development
WORKDIR /app
CMD ["npm", "run", "dev", "-w", "agent-service"]
